[pytest]
log_cli=True
log_level=INFO
markers=
    Regression: covering Regression tests
    Plv: covering Post Live tests
    UnequalParams: covering cartesian product based test parametrization with unequal number of params in fixtures
    EqualParams: covering cartesian product based test parametrization with equal number of params in fixtures
